### ISSUE TITLE
您好，这个项目sql文件还有吗？

### ISSUE THREAD

**Issue by shannxisj** [XiaOkuoAi/Jingdong-fresh#1]
想学习一下

**Comment by XiaOkuoAi** [comment]
应该是这个附件，你看一下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shannxisj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 下午5:15
收件人:&nbsp;"XiaOkuoAi/Jingdong-fresh"<Jingdong-fresh@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[XiaOkuoAi/Jingdong-fresh] 您好，这个项目sql文件还有吗？ (#1)





 
想学习一下

**Comment by shannxisj** [comment]
> 应该是这个附件，你看一下。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"shannxisj"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月12日(星期二) 下午5:15 收件人:&nbsp;"XiaOkuoAi/Jingdong-fresh"<Jingdong-fresh@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[XiaOkuoAi/Jingdong-fresh] 您好，这个项目sql文件还有吗？ (#1) 想学习一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by shannxisj** [comment]
没有附件啊老哥，能重发一下，非常感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"老公"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 下午5:21
收件人:&nbsp;"XiaOkuoAi/Jingdong-fresh"<Jingdong-fresh@noreply.github.com&gt;;
抄送:&nbsp;"you."<1634375550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XiaOkuoAi/Jingdong-fresh] 您好，这个项目sql文件还有吗？ (#1)





 应该是这个附件，你看一下。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"shannxisj"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年5月12日(星期二) 下午5:15 
 收件人:&amp;nbsp;"XiaOkuoAi/Jingdong-fresh"<Jingdong-fresh@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[XiaOkuoAi/Jingdong-fresh] 您好，这个项目sql文件还有吗？ (#1) 
 
 
 
 
 
   
 想学习一下
